version: '3.9'

services:
  dev-env-gui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-env-gui
    privileged: true
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${XAUTHORITY}
    volumes:
      - ${XAUTHORITY}:${XAUTHORITY}
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/work:/home/ubuntu/work
    user: "${UID}:${GID}"
    depends_on:
      - postgres
    networks:
      - devnet
    ports:
      - "8080:8080"

    stdin_open: true     # Keep STDIN open for interactive mode
    tty: true            # Allocate a pseudo-TTY (lets you attach)
    command: bash        # Start in interactive shell

  postgres:
    image: postgres:16
    container_name: postgres-dev
    environment:
      POSTGRES_USER: sapi
      POSTGRES_PASSWORD: sapi
      POSTGRES_DB: furniture
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - devnet

volumes:
  pgdata:

networks:
  devnet:
